import Snake from "./Snake";
import Monster from "./Monster";
import Cubes from "./Cubes";

export default function Npc() {

    return <>
        {/* A working example of using Instance to have multiple renders */}
        <Cubes position={[0, 1, -5]}></Cubes>

        {/* Generated by GLTFJSX. Only one Model loads, doesn't work */}
        <Snake position={[-15, 0, -15]} />
        <Snake position={[-5, 0, -20]} />
        <Snake position={[15, 0, 15]} />
        <Snake position={[5, 0, -5]} />
        
        {/* Normal GLTF Loader. I can't manage to implement Instances on it */}
        <Monster
            name={"Cactoro"}
            position={[10,0,-10]}
            size={4}
            aggressiveness={5}
            walkingSpeed={5}
            chargeSpeed={5}
            roamingDistance={5}
            roamingRotation={1}
            turnFrequency={5}
            damage={5}
            damageSpeed={5}
        />
    </>

}