/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Snake(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("Models/Monsters/Snake_Angry.glb");
  const { actions } = useAnimations(animations, group);
  console.log(nodes.Root)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="SnakeArmature">
          <primitive object={nodes.Root} />
          <group name="Snake">
            <skinnedMesh
              name="Cylinder"
              geometry={nodes.Cylinder.geometry}
              material={materials.DarkGreen}
              skeleton={nodes.Cylinder.skeleton}
            />
            <skinnedMesh
              name="Cylinder_1"
              geometry={nodes.Cylinder_1.geometry}
              material={materials.LightGreen}
              skeleton={nodes.Cylinder_1.skeleton}
            />
            <skinnedMesh
              name="Cylinder_2"
              geometry={nodes.Cylinder_2.geometry}
              material={materials.Yellow}
              skeleton={nodes.Cylinder_2.skeleton}
            />
            <skinnedMesh
              name="Cylinder_3"
              geometry={nodes.Cylinder_3.geometry}
              material={materials.DarkRed}
              skeleton={nodes.Cylinder_3.skeleton}
            />
            <skinnedMesh
              name="Cylinder_4"
              geometry={nodes.Cylinder_4.geometry}
              material={materials.Red}
              skeleton={nodes.Cylinder_4.skeleton}
            />
            <skinnedMesh
              name="Cylinder_5"
              geometry={nodes.Cylinder_5.geometry}
              material={materials.Teeth}
              skeleton={nodes.Cylinder_5.skeleton}
            />
            <skinnedMesh
              name="Cylinder_6"
              geometry={nodes.Cylinder_6.geometry}
              material={materials.Purple}
              skeleton={nodes.Cylinder_6.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("Models/Monsters/Snake_Angry.glb");
